<?php
$this->headLink()->prependStylesheet($this->basePath('css/b-flat.css')); 
?>

<a href="<?=$this->url($this->route, ['action'=>'clear'])?>" class="btn btn-danger">Truncate Database Tables</a>
<a href="<?=$this->url($this->route, ['action'=>'create'])?>" class="btn btn-primary">Populate Database Tables</a>
<hr>
<?php if (!file_exists('./data/files')) { ?>
	<p>
    	Files Directory does not Exist
    	<a href="<?=$this->url($this->route, ['action'=>'createfolders'])?>" class="btn btn-primary">Create Upload Folders</a>
	</p>
<?php } else { ?>
	<p>Files Directory Exists.</p>
<?php } ?>

<div class="row">
	<div class="col">
		<div class="card mb-4">
			<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Checks</b>
        		</div>
        	</div>
        	<div class="card-body">
        		<table class="table table-sm">
                	<thead>
                		<tr>
                			<td>Module One</td>
                		</tr>
                	</thead>
                	<tbody>
                	<?php foreach ($this->checks as $check) : ?>
                		<tr>
                			<td><?=$check['label']?></td>
                			<td>
            				<?php
            				switch ($check['type']) {
            				    case 'checkbox':?>
        				        <div class="checkbox checkbox-slider--b-flat">
                        			<label>
                        				<input type="checkbox" <?=$check['function']?>><span></span>
                        			</label>
                        		</div>
            				    <?    
            				        break;
                                case 'textbox':?>
            				        <input type="text" value="<?=$check['function']?>">
        				        <?
        				            break;
                                default:
                                    break;
            				}
            				?>
                                
                			</td>
                		</tr>
                	<?php endforeach; ?>
                	</tbody>
                </table>
        	</div>
		</div>
	</div>
</div>